---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: vet-service
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: vet-service@sha256:a7364420a5a51bbdff7c838ac62a207efcf15553a92c03f89e2e22cc8a6da986
        namespace: petclinic-develop
      name: 1.5.9
